# Generated by Django 5.2.5 on 2025-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sleep_hours', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('glucose', models.FloatField()),
            ],
        ),
    ]
