# Generated by Django 5.2.5 on 2025-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='spo2',
            field=models.IntegerField(default=98),
        ),
    ]
